service: bluebird-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1
  memorySize: 512
  timeout: 30
  httpApi:
    cors:
      allowedOrigins:
        - https://main.d1jaxwhav3ibk1.amplifyapp.com
        - http://localhost:5173
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
        - HEAD
  environment:
    SECRETS_ID: ${self:custom.secretsId}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${self:custom.secretsId}

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          method: GET
          path: /{proxy+}
      - httpApi:
          method: POST
          path: /{proxy+}
      - httpApi:
          method: PUT
          path: /{proxy+}
      - httpApi:
          method: PATCH
          path: /{proxy+}
      - httpApi:
          method: DELETE
          path: /{proxy+}
      - httpApi:
          method: HEAD
          path: /{proxy+}
      - httpApi:
          method: OPTIONS
          path: /{proxy+}

plugins:
  - serverless-offline

package:
  patterns:
    - '!**'
    - src/**
    - package.json
    - package-lock.json
    - node_modules/**
    - '!node_modules/.bin/**'
    - '!node_modules/aws-sdk/**'
    - ../docs/openapi.yaml

custom:
  secretsId: ${env:SECRETS_ID}
